# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ''
subtitle: ''
description: ''
keywords:
author: 
language: zh-CN
timezone: ''

# 网址图标 favicon
favicon: /img/logo/avatar.png

nav:
  logo: /img/logo/avatar.png
  display_title: true
  fixed: false # fixed navigation bar

menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    旅游: /tour/ || fas fa-mountain-sun
    音乐: /music/ || fas fa-music
    相册: /gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  关于: /about/ || fas fa-heart

# 社交
social:
  fab fa-github: https://github.com/lzwStore || Github || "#hdhfbb"
  # fas fa-envelope: mailto:xxxxxx@gmail.com || Email || "#000000"

# 侧边栏
aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  card_announcement: fasle #公告卡片
  # card_categories: true #分类卡片
  card_archives: true #归档卡片
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/lzwStore


# 头像
avatar:
  img: /img/logo/avatar.png
  effect: false # 頭像會一直轉圈

# 文章头图
top_img: ''
default_top_img: /img/cover.png

# 文章封面
cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: left
  # 文章封面 - 当文章没有展示图是默认展示这个图
  default_cover: /img/2.png

# 主页的Meta展示
post_meta:
  page:
    date_type: both # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

# 主题展示
darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  autoChangeMode: false
  # Set the light mode time. The value is between 0 and 24. If not set, the default value is 6 and 18
  start: # 8
  end: # 22

# 禁用头图
disable_top_img: false

# 主页封面图
index_img: transparent

# Website Background (設置網站背景)
# 网站背景图
background: url(/images/10001.png)

# Footer Background
footer_bg: transparent

# Add mask to header or footer (为 header 或 footer 添加黑色半透遮罩)
mask:
  header: false

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
# 代码主题
highlight_theme: pale night
# 代码复制
highlight_copy: true
# 代码高度
highlight_height_limit: 500 # unit: px
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
# time_format: 
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# canvas_nest
# https://github.com/hustcc/canvas-nest.js
# canvas 背景粒子效果
canvas_nest:
  enable: false
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false

# 赞赏
reward:
  enable: false
  QR_code:
   # - img: /img/wechat.jpg
   #   link:
   #   text: wechat
   # - img: /img/alipay.jpg
   #   link:
   #   text: alipay

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

error_404:
  enable: true
  subtitle: "頁面沒有找到"
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.pagination

inject:
  # 自定义css
  head:
    # 顶部进度条
    - <link rel="stylesheet" href="/css/progress.css">
    # 背景css
    - <link rel="stylesheet" href="/css/background.css">
  # 自定义js
  bottom:
    - <script src="//cdn.bootcss.com/pace/1.0.2/pace.min.js"></script>
    # 音乐播放器
    # - <script src="https://myhkw.cn/player/js/jquery.min.js" type="text/javascript"></script>
    # - <script src="https://myhkw.cn/api/player/demo" id="myhk" key="demo" skin="player" lr="l" m="1"></script>

# Deployment
deploy:
  type: git
  repo:
    github:
      url: https://github.com/lzwStore/lzwStore.github.io.git  # 记得把username替换为自己的用户名
      branch: main #2020年10月后github新建仓库默认分支改为main，注意修改
    # 也可以用另一种写法,二选一即可
    # github: git@github.com:username/username.github.io.git,master
